// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scheduler.Web.Data;

#nullable disable

namespace Scheduler.Web.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    [Migration("20251008062520_FixRangeMapping")]
    partial class FixRangeMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Scheduler.Domain.Entities.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScheduleBlockId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleBlockId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Scheduler.Domain.Entities.Presenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScheduleBlockId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleBlockId");

                    b.ToTable("Presenters");
                });

            modelBuilder.Entity("Scheduler.Domain.Entities.ScheduleBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduleDayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Studio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleDayId");

                    b.ToTable("ScheduleBlocks");
                });

            modelBuilder.Entity("Scheduler.Domain.Entities.ScheduleDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScheduleDays");
                });

            modelBuilder.Entity("Scheduler.Domain.Entities.Guest", b =>
                {
                    b.HasOne("Scheduler.Domain.Entities.ScheduleBlock", null)
                        .WithMany("Guests")
                        .HasForeignKey("ScheduleBlockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scheduler.Domain.Entities.Presenter", b =>
                {
                    b.HasOne("Scheduler.Domain.Entities.ScheduleBlock", null)
                        .WithMany("Presenters")
                        .HasForeignKey("ScheduleBlockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scheduler.Domain.Entities.ScheduleBlock", b =>
                {
                    b.HasOne("Scheduler.Domain.Entities.ScheduleDay", null)
                        .WithMany("Blocks")
                        .HasForeignKey("ScheduleDayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Scheduler.Domain.ValueObjects.TimeOfDayRange", "Range", b1 =>
                        {
                            b1.Property<int>("ScheduleBlockId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("End")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("EndTime");

                            b1.Property<string>("Start")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("StartTime");

                            b1.HasKey("ScheduleBlockId");

                            b1.ToTable("ScheduleBlocks");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleBlockId");
                        });

                    b.Navigation("Range")
                        .IsRequired();
                });

            modelBuilder.Entity("Scheduler.Domain.Entities.ScheduleBlock", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Presenters");
                });

            modelBuilder.Entity("Scheduler.Domain.Entities.ScheduleDay", b =>
                {
                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
